cudnn:                                    # [linux64]
  - undefined                             # [linux64]
cuda_compiler_version:                    # [linux64]
  - None                                  # [linux64]
docker_image:                             # [linux64]
  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                 # [linux64]
  - cos7                                  # [linux64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
